### PR TITLE
startup: Use inbuilt electron API for autostartup.

### LINKED ISSUE #851: Zulip not starting up in Windows
---

- **Operating System**:
  - [x] Windows
  - [ ] Linux/Ubuntu
  - [ ] macOS
- **Clear steps to reproduce the issue**:
Simply install latesst version v4.0.0, ensure in settings startup at login enabled  and restart
- **Relevant error messages and/or screenshots**:
The zulip app is not started on startup (not on main desktop nor in system tray)

### PR DESCRIPTION
**Pull request by vsvipul**
**What's this PR do?**
Switch from using external auto-launch module to
inbuilt setLoginItemSettings for windows and macos,
as some users reported issues on windows.
Fixes #851.

@akashnimare @kanishk98  Need to test this on windows and macos. Can you do it ?

**You have tested this PR on:**
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS

### CODE REVIEW

File: app/main/startup.ts [hunk 1]
```diff
@@ -11,21 +11,23 @@ export const setAutoLaunch = (AutoLaunchValue: boolean): void => {
...
-		isHidden: false
-	});
 	const autoLaunchOption = ConfigUtil.getConfigItem('startAtLogin', AutoLaunchValue);
 
-	if (autoLaunchOption) {
-		ZulipAutoLauncher.enable();
+	// setLoginItemSettings doesn't support linux
+	if (process.platform === 'linux') {
+		const ZulipAutoLauncher = new AutoLaunch({
+			name: 'Zulip',
```
Comment (akashnimare) [inline app/main/startup.ts:19]: @vsvipul you removed the path arg here.

**Review by akashnimare — CHANGES_REQUESTED** [review]

**Comment by akashnimare** [comment]
Left a comment. Otherwise all good.

**Comment by akashnimare** [comment]
@vsvipul I can merge this real quick if you can make those changes.

File: app/main/startup.ts (hunk 1 above)
Comment (vsvipul) [reply app/main/startup.ts:19]: @akashnimare  We were changing the path only for mac previously and using the default for linux. As we now use AutoLaunch for only linux, this is no longer required. See https://www.npmjs.com/package/auto-launch .
```
For NW.js and Electron apps, you don't have to specify the path. We guess based on process.execPath.
```

**Comment by vsvipul** [comment]
@akashnimare I have addressed the issue. Before merging, please test this on mac and windows too as I haven't done so.

**Comment by akashnimare** [comment]
Works well on macOS.

File: app/main/startup.ts (hunk 1 above)
Comment (akashnimare) [reply app/main/startup.ts:19]: Got it. But do we need to update the auto-launch version?

Comment (vsvipul) [reply app/main/startup.ts:19]: We are already on the latest version i.e. 5.0.5 .

**Comment by parthi2929** [comment]
so current change is failing in windows? @akashnimare

**Comment by akashnimare** [comment]
Tested on Windows, works as expected. Merging. @parthi2929 this will be added in the next release.
