### PR TITLE
Generate User-Agent when app starts, thus avoiding storing it on disk

### LINKED ISSUE #921: User-Agent is incorrectly cached in settings.json, with stale value remembered on upgrades
We seem to be saving and restoring (part of) the User-Agent in `settings.json`, leading to self-contradictory user-agents like

`ZulipElectron/5.0.0 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Zulip/4.0.3 Chrome/66.0.3359.181 Electron/3.1.10 Safari/537.36`

(Note the `ZulipElectron/5.0.0` and `Zulip/4.0.3`.)

This setting seems to have been added in #818. There should be no reason to persist the User-Agent to disk at all. Why are we doing that?

Cc @kanishk98

### PR DESCRIPTION
**Pull request by manavmehta**
Fixes: #921 

**What's this PR do?**
Fetch and send UA from main process and use ipc call to catch it in renderer process: system-util.ts and use it elsewhere in the app as required, avoiding storing it on disk.

**Any background context you want to provide?**
Please refer #921 

**You have tested this PR on:**
  - [ ] Linux/Ubuntu
  - [X] macOS Catalina 10.15.2

### CODE REVIEW

**Comment by manavmehta** [comment]
@andersk @timabbott Can you please have a look? If this feels right, we can refine it :)

**Comment by timabbott** [comment]
This certainly looks plausible.  It's probably a good idea to test this against a Zulip development server configured with a Python `print()` statement to print the User-Agent it received in both `GET /server_settings` and `GET /events` to confirm it's sending the right data in both contexts.

File: app/renderer/js/utils/system-util.ts [hunk 1]
```diff
@@ -16,6 +14,19 @@ export const connectivityERR: string[] = [
...
+ipcRenderer.on('user-agent', (event, arg) => {
+	userAgent = arg;
+	if (!userAgent) {
+		console.log('User-Agent found null');
+	}
+});
+
+// This is to remove the UA setting from the disk if the app is not freshly installed
+// We should remove this in a further release
+if (isConfigItemExists('userAgent')) {
```
Comment (akashnimare) [inline app/renderer/js/utils/system-util.ts]: @manavmehta we should put this where we initialize other settings?

File: app/renderer/js/utils/system-util.ts [hunk 2]
```diff
@@ -32,14 +43,9 @@ export function getOS(): string {
 		return '';
 	}
 }
-
-export function setUserAgent(webViewUserAgent: string): void {
```
Comment (akashnimare) [inline app/renderer/js/utils/system-util.ts:36]: We need to use this with the session's UA. We are using `ZulipElectron` to detect the desktop app. Check out -
https://github.com/zulip/zulip/search?q=ZulipElectron&unscoped_q=ZulipElectron

cc @timabbott

**Review by akashnimare — CHANGES_REQUESTED** [review]

File: app/renderer/js/utils/system-util.ts (hunk 2 above)
Comment (manavmehta) [reply app/renderer/js/utils/system-util.ts:36]: @akashnimare Maybe we should refine `test_insecure_desktop_app(self)` itself? (wrt desktop app only)
As looking at L101, isn't this exactly what @andersk pointed out? As this forces us to append `ZulipElectron/${app.getVersion()}` to the UA.

https://github.com/zulip/zulip/blob/17723b16177663a558c03ef6a41a926163ce4241/zerver/tests/test_compatibility.py#L101

**Comment by akashnimare** [comment]
@manavmehta can you test this against a zulip test server and note down the UA in the following cases -
a) When user add a new server
b) API requests from the renderer process

**Comment by manavmehta** [comment]
null_UA_on_adding_server
The UA is correct in /server_settings and /events
But it is sent as null (or the default value) while adding a server, thereafter, it is correct in renderer API calls.

Reason: The new-server-form calls domain-util which calls system-utils afresh.

Workaround as suggested by @abhigyank  ebb1238
Change the default value of UA
This would work because:
1. This is the only part we use to recognize Desktop app
2. A user adds server least often.

@timabbott @andersk any fixes in your mind or should we go with this?
(documenting this a TODO so that someone could come up with a fix)

**Comment by andersk** [comment]
A more robust approach would be for the renderer process to ask the main process for the user-agent with `ipcRenderer.invoke` (caching the resulting `Promise`) or `ipcRenderer.sendSync` (caching the resulting string).

**Comment by manavmehta** [comment]
@andersk That was a great suggestion.
It is ready for review and merge from my side.
cc: @akashnimare 

P.S. If you want, I can send you the log where I printed a bunch of UAs received by the test server

File: app/renderer/js/utils/system-util.ts [hunk 3]
```diff
@@ -32,14 +34,9 @@ export function getOS(): string {
...
-	userAgent = `ZulipElectron/${app.getVersion()} ${webViewUserAgent}`;
-}
-
 export function getUserAgent(): string | null {
 	if (!userAgent) {
-		setUserAgent(ConfigUtil.getConfigItem('userAgent', null));
+		console.log('userAgent found null');
```
Comment (kanishk98) [inline app/renderer/js/utils/system-util.ts]: Hmm, I don't think using a `console.log()` statement is a great idea - we're already logging the UA sent on the server side, right?
Maybe we can use a Sentry call here instead if we do client-side logs.

File: app/renderer/js/main.ts [hunk 4]
```diff
@@ -239,6 +240,14 @@ class ServerManagerView {
 		this.toggleSidebar(showSidebar);
 	}
 
+	/*  Removes the stale UA string from the disk if the app is not freshly installed
+		We should remove this in a further release	*/
+	removeUAfromDisk(): void {
+		if (ConfigUtil.isConfigItemExists('userAgent')) {
```
Comment (kanishk98) [inline app/renderer/js/main.ts]: Do we need this conditional? I believe the db handles that for us, doesn't it?

File: app/main/index.ts [hunk 5]
```diff
@@ -185,15 +185,18 @@ app.on('ready', () => {
...
 		}
-		if (!ConfigUtil.isConfigItemExists('userAgent')) {
-			const userAgent = session.fromPartition('webview:persistsession').getUserAgent();
-			ConfigUtil.setConfigItem('userAgent', userAgent);
-		}
+	});
+
+	ipcMain.handle('fetch-user-agent', async () => {
+		const userAgent = session.fromPartition('webview:persistsession').getUserAgent();
+		return userAgent;
```
Comment (kanishk98) [inline app/main/index.ts]: Sorry, another nitpick, would you mind just returning the result of the expression directly?
I don't see the need to declare a `const` here.

**Review by kanishk98 — COMMENTED** [review]
Alright, this looks good to me, except for a few comments I've left that you may want to consider. 
Great work, @manavmehta!

File: app/main/index.ts (hunk 5 above)
Comment (manavmehta) [reply app/main/index.ts]: Sure

File: app/renderer/js/main.ts (hunk 4 above)
Comment (manavmehta) [reply app/renderer/js/main.ts]: Probably it does. I was a little unsure about that. But you confirmed it for me. Thanks!

File: app/renderer/js/utils/system-util.ts (hunk 3 above)
Comment (manavmehta) [reply app/renderer/js/utils/system-util.ts]: @kanishk98 I've changed the process from console.log() to logger.log()
DO let me know if there is a need to make a Sentry call :)
@akashnimare what would you suggest?

**Comment by manavmehta** [comment]
@kanishk98 Thanks. Will push the changes ASAP as the logging part is confirmed :)

**Comment by andersk** [comment]
The goal is to avoid the race condition where we see `ZulipElectron/5.0.0 ` for some time at startup instead of the full `ZulipElectron/5.0.0 Mozilla/5.0 blah/blah blah` string. Your code still doesn’t do that.

Either use `ipcRenderer.invoke` this way:

```ts
const userAgentPromise: Promise<str> = ipcRenderer.invoke('fetch-user-agent');

export async function getUserAgent(): string {
    return `ZulipElectron/${app.getVersion()} ${await userAgentPromise}`;
}
```

(which requires adjusting its callers to be `async` as well), or use `ipcRenderer.sendSync`.

**Comment by manavmehta** [comment]
@andersk I tested 37c420a against Zulip test server and logging both. Couldn't find a single instance of the race condition.

But since theoretically, the condition is possible, I think we may go with `ipcRenderer.sendSync`
Tested it and it works fine. Plus, since it fetches UA synchronously, I don't think there's a possibility for the race condition.

Though it adds a delay, which is probably lesser than a millisecond and better than the race condition anyway.
Thanks :)

File: app/main/index.ts [hunk 6]
```diff
@@ -185,15 +185,17 @@ app.on('ready', () => {
 	const page = mainWindow.webContents;
 
 	page.on('dom-ready', () => {
+		// On dom-ready, fetch user agent and send to renderer processes.
+		// As of now, only system-util.ts catches it.
```
Comment (andersk) [inline app/main/index.ts]: This comment is wrong now since we don’t wait for `dom-ready` (and I don’t think there’s a reason to wait).

File: app/renderer/js/utils/system-util.ts [hunk 7]
```diff
@@ -32,14 +36,9 @@ export function getOS(): string {
...
-
-export function setUserAgent(webViewUserAgent: string): void {
-	userAgent = `ZulipElectron/${app.getVersion()} ${webViewUserAgent}`;
-}
-
 export function getUserAgent(): string | null {
 	if (!userAgent) {
-		setUserAgent(ConfigUtil.getConfigItem('userAgent', null));
+		logger.log('userAgent found null');
 	}
```
Comment (andersk) [inline app/renderer/js/utils/system-util.ts]: Remove this `if` branch, the `null` from the return type, and the logger. No reason to have a bunch of code for an impossible case.

Comment (manavmehta) [reply app/renderer/js/utils/system-util.ts]: My bad. Should've removed this in prev commit.
Refactored

**Comment by andersk** [comment]
I edited this to use `ses.setUserAgent` to set the User-Agent once for the entire session rather than individually for each webview. I also squashed all the commits together.
