### PR TITLE
webview: Work around buggy focus switching in Electron 3.0.10

### LINKED ISSUE #634: Incorrect Focus after Switching Realms
Running on the latest master. 
When I switch between Realms, I have to click to change focus to the new realm.  To reproduce, 

- add two (or more) realms to Zulip electron
- open compose box in the first realms
- switch to the second realm using the short cut key (Ctrl + 2)
- try using navigation shortcuts - n, j, k, etc. Notice that things don't work! 
- Click on the "page" to bring it into focus. Try the navigation shortcuts now. 
- switch back to the first realm (Ctrl + 1)
- Notice all the previously tried shortcuts typed out in the compose box.

### PR DESCRIPTION
**Pull request by punchagan**
This commit works around a couple of bugs, which seem to be upstream bugs in the
current version of Electron.

First, `webContents.isFocused()` seems to be true even if we just switched to
a tab, and are trying to set it as the focused element. To workaround this, we
check if the `webview` element is the same as `document.activeElement`.

Also, as per https://github.com/electron/electron/issues/15718, it looks like
`blur` needs to be called on the currently active element, before switching
focus to another element i.e., calling `focus` on it.

Closes #634

### CODE REVIEW

File: app/renderer/js/components/webview.js [hunk 1]
```diff
@@ -165,7 +165,13 @@ class WebView extends BaseComponent {
 	focus() {
 		// focus Webview and it's contents when Window regain focus.
 		const webContents = this.$el.getWebContents();
-		if (webContents && !webContents.isFocused()) {
+		// HACK: webContents.isFocused() seems to be true even without the element
+		// being in focus. So, we check against `document.activeElement`.
+		if (!(this.$el === document.activeElement)) {
```
Comment (vsvipul) [inline app/renderer/js/components/webview.js]: Why not use simple !== condition ? Also, we need an if condition for webContents here, because we are focusing on it later on. Rest of it seems fine. Solves the issue. LGTM ! :)

**Review by vsvipul — APPROVED** [review]

File: app/renderer/js/components/webview.js (hunk 1 above)
Comment (punchagan) [reply app/renderer/js/components/webview.js]: Thanks @vsvipul  for the review. I've pushed changes addressing your comments

**Comment by akashnimare** [comment]
Merged. Thanks, @punchagan. Excellent commit message 🙇

**Comment by punchagan** [comment]
Thanks, @akashnimare! :grinning:
