### PR TITLE
sidebar: Fixes to org cycling

### LINKED ISSUE #691: Issues with Ctrl+Tab cycling
Follow up issues of #663

* While on the first server, Ctrl+Shift+Tab doesn't work. Should go to last active webview.
* Open settings, start cycling using Ctrl+Tab - while on settings webview, the settings icon the sidebar is not highlighted. Settings icon should be highlighted.

### PR DESCRIPTION
**Pull request by vsvipul**
**What's this PR do?**
Fixes #691.

Two changes made-
1. Ctrl+Shift+Tab wasn't working for first org. It should change the active realm to last realm.
2. Disabled org cycling with ctrl+tab on non-server pages.

**You have tested this PR on:**
  - [ ] Windows
  - [x] Linux/Ubuntu
  - [ ] macOS

### CODE REVIEW

File: app/main/menu.js [hunk 1]
```diff
@@ -447,6 +449,23 @@ class AppMenu {
 	static checkForUpdate() {
 		appUpdater(true);
 	}
+
+	static getNextServer(tabs, activeTabIndex) {
```
Comment (kanishk98) [inline app/main/menu.js:453]: I'm not sure why these methods are required. I guess you're trying to make sure that the user doesn't enter the settings webview - but that doesn't happen anyway. Doesn't the simple `(activeTabIndex + 1) % tabs.length` formula work for this?

Comment (vsvipul) [reply app/main/menu.js:453]: No, it doesn't. Try opening settings, then go to first org and cycle through using Ctrl+Tab, settings will open up.

Comment (kanishk98) [reply app/main/menu.js:453]: Ah right, my bad. Awesome, it works as expected. :)

**Review by abhigyank — APPROVED** [review]
Works as expected. Fixes the issues from the previous PR. Can be merged.

**Comment by akashnimare** [comment]
Thanks, everyone 🚀
